spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 266978972332-k0oi6ke433g6ei92nsuu3nav44utlpvn.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
